# MySQL. Versions 5.1.10 and up are supported.
#
default: &default

  #RDSデータベース
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: illustlifeDB
  pool: 5
  username: rio
  password: Orino_1013
  socket: /var/lib/mysql/mysql.sock
  host: illustlife2.cczbbshsk7se.ap-northeast-1.rds.amazonaws.com

development:
  <<: *default
  database: illustlife_development

test:
  <<: *default
  database: illustlife_test

#   production:
#     url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: illustlifeDB
